### ISSUE TITLE
zaddIncr syntax error

### ISSUE THREAD

**Issue by ewired** [denodrivers/redis#286]
It looks like zaddIncr may be affected by the same issue as #284.
```js
> await r.zaddIncr("a", 1, "b")
Uncaught Error: -ERR syntax error

    at tryParseErrorReply (https://deno.land/x/redis@v0.25.1/protocol/reply.ts:205:11)
    at readReply (https://deno.land/x/redis@v0.25.1/protocol/reply.ts:55:7)
```

**Comment by uki00a** [comment]
Thanks for the report @ewired! This is now fixed in the latest version ([v0.25.2](https://deno.land/x/redis@v0.25.2))
